"""PDF report export service for verification results."""

from __future__ import annotations

from datetime import datetime
import html
from pathlib import Path
import unicodedata

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.platypus import HRFlowable, Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from config import C_AMBER, C_AMBER_BG, C_DANGER, C_DANGER_BG, C_NAVY, C_SUCCESS, C_SUCCESS_BG
from utils.logger import get_logger


class _NumberedCanvas(canvas.Canvas):
    """Canvas that renders page numbers as X of Y in the footer."""

    def __init__(self, *args, generated_timestamp: str, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict] = []
        self._generated_timestamp = generated_timestamp

    def showPage(self) -> None:  # noqa: N802
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self) -> None:  # noqa: A003
        self._saved_page_states.append(dict(self.__dict__))
        total_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_footer(total_pages)
            super().showPage()
        super().save()

    def _draw_footer(self, total_pages: int) -> None:
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#6B7280"))
        footer_text = (
            "Generated by SignVerify Pro AI Verification System · "
            f"{self._generated_timestamp} · Page {self._pageNumber} of {total_pages}"
        )
        self.drawCentredString(A4[0] / 2.0, 1.2 * cm, footer_text)


class ExportService:
    """Generates professional PDF reports from verification payloads."""

    def __init__(self) -> None:
        self.logger = get_logger("export_service")

    def _build_styles(self) -> dict[str, ParagraphStyle]:
        base = getSampleStyleSheet()
        return {
            "title": ParagraphStyle(
                "title",
                parent=base["Title"],
                fontName="Helvetica-Bold",
                fontSize=20,
                leading=24,
                textColor=colors.HexColor(C_NAVY),
                alignment=1,
                spaceAfter=4,
            ),
            "subtitle": ParagraphStyle(
                "subtitle",
                parent=base["Normal"],
                fontName="Helvetica",
                fontSize=10,
                leading=14,
                textColor=colors.HexColor("#6B7280"),
                alignment=1,
                spaceAfter=10,
            ),
            "heading": ParagraphStyle(
                "heading",
                parent=base["Heading2"],
                fontName="Helvetica-Bold",
                fontSize=13,
                leading=16,
                textColor=colors.HexColor(C_NAVY),
                spaceAfter=4,
            ),
            "body": ParagraphStyle(
                "body",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=10,
                leading=14,
                textColor=colors.HexColor("#1A1A2E"),
            ),
            "caption": ParagraphStyle(
                "caption",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=8,
                leading=10,
                alignment=1,
                textColor=colors.HexColor("#6B7280"),
            ),
            "verdict": ParagraphStyle(
                "verdict",
                parent=base["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=18,
                leading=22,
                textColor=colors.HexColor(C_NAVY),
            ),
            "footnote": ParagraphStyle(
                "footnote",
                parent=base["BodyText"],
                fontName="Helvetica-Oblique",
                fontSize=8,
                leading=11,
                textColor=colors.HexColor("#6B7280"),
            ),
        }

    def _draw_page_header(self, canv: canvas.Canvas, doc: SimpleDocTemplate) -> None:
        canv.saveState()
        top_y = A4[1] - 1.6 * cm

        canv.setFillColor(colors.HexColor(C_NAVY))
        canv.setFont("Helvetica-Bold", 16)
        canv.drawString(doc.leftMargin, top_y, "SignVerify Pro")

        canv.setFillColor(colors.HexColor(C_DANGER))
        canv.setFont("Helvetica-Bold", 9)
        canv.drawRightString(A4[0] - doc.rightMargin, top_y + 1, "CONFIDENTIAL")

        canv.setStrokeColor(colors.HexColor(C_NAVY))
        canv.setLineWidth(1)
        canv.line(doc.leftMargin, top_y - 6, A4[0] - doc.rightMargin, top_y - 6)
        canv.restoreState()

    def _safe_filename(self, path_value: str) -> str:
        if not path_value:
            return ""
        return Path(path_value).name

    def _normalize_pdf_text(self, value: object, preserve_newlines: bool = False) -> str:
        text = str(value or "")
        text = text.replace("\r\n", "\n").replace("\r", "\n")
        text = unicodedata.normalize("NFKC", text)

        replacements = {
            "\u2013": "-",
            "\u2014": "-",
            "\u2022": "*",
            "\u2018": "'",
            "\u2019": "'",
            "\u201c": '"',
            "\u201d": '"',
            "\u2026": "...",
        }
        for source, target in replacements.items():
            text = text.replace(source, target)

        filtered_chars: list[str] = []
        for char in text:
            code = ord(char)
            if char == "\n" or char == "\t" or code >= 32:
                if code <= 255:
                    filtered_chars.append(char)
                else:
                    filtered_chars.append("?")

        escaped = html.escape("".join(filtered_chars), quote=False)
        if preserve_newlines:
            return escaped.replace("\n", "<br/>")
        return escaped

    def _build_image_cell(
        self,
        image_path: str,
        image_label: str,
        styles: dict[str, ParagraphStyle],
    ) -> list:
        safe_image_label = self._normalize_pdf_text(image_label)
        flowables: list = [Paragraph(f"<b>{safe_image_label}</b>", styles["caption"]), Spacer(1, 6)]

        image_exists = bool(image_path) and Path(image_path).exists()
        if image_exists:
            image_flowable = Image(image_path)
            image_flowable._restrictSize(200, 80)
            flowables.append(image_flowable)
        else:
            placeholder = Table(
                [["Image not available"]],
                colWidths=[200],
                rowHeights=[80],
            )
            placeholder.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F0F0F0")),
                        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#D0D5DD")),
                        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#6B7280")),
                        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                        ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ]
                )
            )
            flowables.append(placeholder)

        flowables.append(Spacer(1, 5))
        filename = self._safe_filename(image_path)
        flowables.append(Paragraph(self._normalize_pdf_text(filename), styles["caption"]))
        return flowables

    def generate_report(self, verification_data: dict, output_path: str) -> str:
        try:
            output = Path(output_path)
            output.parent.mkdir(parents=True, exist_ok=True)

            styles = self._build_styles()
            generated_timestamp = datetime.now().strftime("%d %b %Y %H:%M")

            doc = SimpleDocTemplate(
                str(output),
                pagesize=A4,
                leftMargin=2 * cm,
                rightMargin=2 * cm,
                topMargin=2 * cm,
                bottomMargin=2 * cm,
                title="SignVerify Pro Verification Report",
                author="SignVerify Pro",
            )

            verdict = str(
                verification_data.get("verdict")
                or verification_data.get("result")
                or "INCONCLUSIVE"
            ).upper()
            confidence = float(verification_data.get("confidence", 0.0) or 0.0)
            confidence_pct = f"{max(0.0, min(1.0, confidence)) * 100.0:.1f}%"
            mode = str(verification_data.get("mode", ""))
            person_name = str(verification_data.get("person_name", "Ad-Hoc Comparison"))
            verification_id = verification_data.get("verification_id", "N/A")
            verified_at = verification_data.get("verified_at", generated_timestamp)
            reason = str(verification_data.get("reason", "No forensic reasoning provided."))
            response_hash = str(verification_data.get("response_hash", "N/A"))

            safe_verdict = self._normalize_pdf_text(verdict)
            safe_confidence_pct = self._normalize_pdf_text(confidence_pct)
            safe_mode = self._normalize_pdf_text(mode)
            safe_person_name = self._normalize_pdf_text(person_name)
            safe_verification_id = self._normalize_pdf_text(verification_id)
            safe_verified_at = self._normalize_pdf_text(verified_at)
            safe_reason = self._normalize_pdf_text(reason, preserve_newlines=True)

            verdict_palette = {
                "MATCH": (colors.HexColor(C_SUCCESS_BG), colors.HexColor(C_SUCCESS)),
                "MISMATCH": (colors.HexColor(C_DANGER_BG), colors.HexColor(C_DANGER)),
                "INCONCLUSIVE": (colors.HexColor(C_AMBER_BG), colors.HexColor(C_AMBER)),
            }
            summary_bg, verdict_text_color = verdict_palette.get(
                verdict,
                (colors.HexColor(C_AMBER_BG), colors.HexColor(C_AMBER)),
            )
            verdict_style = ParagraphStyle("verdict_dynamic", parent=styles["verdict"], textColor=verdict_text_color)

            story: list = []

            story.append(Spacer(1, 1.6 * cm))
            story.append(Paragraph("Signature Verification Report", styles["title"]))
            story.append(Paragraph("AI-Assisted Forensic Analysis · SignVerify Pro", styles["subtitle"]))
            story.append(Spacer(1, 8))

            summary_table = Table(
                [
                    [
                        Paragraph(f"<b>{safe_verdict}</b>", verdict_style),
                        Paragraph(f"<b>Confidence:</b> {safe_confidence_pct}", styles["body"]),
                    ],
                    [
                        Paragraph(f"<b>Mode:</b> {safe_mode}", styles["body"]),
                        Paragraph(f"<b>Person Name:</b> {safe_person_name}", styles["body"]),
                    ],
                    [
                        Paragraph(f"<b>Verification ID:</b> {safe_verification_id}", styles["body"]),
                        Paragraph(f"<b>Timestamp:</b> {safe_verified_at}", styles["body"]),
                    ],
                ],
                colWidths=[doc.width * 0.5, doc.width * 0.5],
            )
            summary_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), summary_bg),
                        ("BOX", (0, 0), (-1, -1), 1.5, verdict_text_color),
                        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E0E4EC")),
                        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                        ("LEFTPADDING", (0, 0), (-1, -1), 10),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                        ("TOPPADDING", (0, 0), (-1, -1), 8),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ]
                )
            )
            story.append(summary_table)
            story.append(Spacer(1, 14))

            story.append(Paragraph("Signature Images", styles["heading"]))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor(C_NAVY), spaceAfter=8))

            reference_path = str(verification_data.get("reference_image_path", "") or "")
            submitted_path = str(verification_data.get("submitted_image_path", "") or "")
            images_table = Table(
                [
                    [
                        self._build_image_cell(reference_path, "Reference Signature", styles),
                        self._build_image_cell(submitted_path, "Submitted Signature", styles),
                    ]
                ],
                colWidths=[doc.width * 0.5, doc.width * 0.5],
            )
            images_table.setStyle(
                TableStyle(
                    [
                        ("VALIGN", (0, 0), (-1, -1), "TOP"),
                        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E0E4EC")),
                        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E0E4EC")),
                        ("LEFTPADDING", (0, 0), (-1, -1), 8),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                        ("TOPPADDING", (0, 0), (-1, -1), 8),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ]
                )
            )
            story.append(images_table)
            story.append(Spacer(1, 14))

            story.append(Paragraph("Forensic Reasoning", styles["heading"]))
            reasoning_box = Table([[Paragraph(safe_reason, styles["body"])]], colWidths=[doc.width])
            reasoning_box.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F5F7FA")),
                        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#E0E4EC")),
                        ("LEFTPADDING", (0, 0), (-1, -1), 8),
                        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                        ("TOPPADDING", (0, 0), (-1, -1), 8),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ]
                )
            )
            story.append(reasoning_box)
            story.append(Spacer(1, 14))

            story.append(Paragraph("Forensic Observations (25 Dimensions)", styles["heading"]))

            observations = verification_data.get("observations") or {}
            if not isinstance(observations, dict):
                observations = {}
            observation_ratings: list[str] = []
            observation_rows = [[Paragraph("<b>Feature</b>", styles["body"]), Paragraph("<b>Similarity Assessment</b>", styles["body"])]]
            for feature, rating in observations.items():
                feature_label = self._normalize_pdf_text(str(feature).replace("_", " ").title())
                rating_raw = str(rating or "Unable to Assess")
                rating_value = self._normalize_pdf_text(rating_raw)
                observation_ratings.append(rating_raw)
                observation_rows.append([Paragraph(feature_label, styles["body"]), Paragraph(rating_value, styles["body"])])

            observations_table = Table(
                observation_rows,
                colWidths=[doc.width * 0.6, doc.width * 0.4],
                repeatRows=1,
            )

            table_style_commands = [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EEF2F7")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor(C_NAVY)),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D9DEE8")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]

            for row_index in range(1, len(observation_rows)):
                feature_bg = colors.HexColor("#FFFFFF") if row_index % 2 else colors.HexColor("#FAFBFC")
                table_style_commands.append(("BACKGROUND", (0, row_index), (0, row_index), feature_bg))

                rating_text = observation_ratings[row_index - 1].strip().lower()
                if rating_text == "high":
                    rating_bg = colors.HexColor(C_SUCCESS_BG)
                elif rating_text == "medium":
                    rating_bg = colors.HexColor(C_AMBER_BG)
                elif rating_text == "low":
                    rating_bg = colors.HexColor(C_DANGER_BG)
                else:
                    rating_bg = colors.HexColor("#F0F0F0")
                table_style_commands.append(("BACKGROUND", (1, row_index), (1, row_index), rating_bg))

            observations_table.setStyle(TableStyle(table_style_commands))
            story.append(observations_table)
            story.append(Spacer(1, 12))

            footer_note = (
                "This report was generated automatically by SignVerify Pro using SignVerify Pro multimodal "
                "AI analysis. It constitutes an AI-assisted forensic assessment and does not replace a formal "
                "examination by a Certified Forensic Document Examiner (FDE). "
                f"Verification ID: {verification_id} · SHA-256 Hash: {response_hash}"
            )
            story.append(Paragraph(self._normalize_pdf_text(footer_note), styles["footnote"]))

            doc.build(
                story,
                onFirstPage=self._draw_page_header,
                onLaterPages=self._draw_page_header,
                canvasmaker=lambda *args, **kwargs: _NumberedCanvas(
                    *args,
                    generated_timestamp=generated_timestamp,
                    **kwargs,
                ),
            )

            self.logger.info("PDF report generated: %s", output)
            return str(output)
        except Exception as exc:
            self.logger.exception("Failed to generate PDF report")
            raise RuntimeError(f"Unable to generate PDF report: {exc}") from exc
